(()=>{
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const ensureMeta=()=>{if(!window.G)return null;G.balance=G.balance||{version:2,form:[],matches:0};return G.balance};
function userFormBoost(){const b=ensureMeta();if(!b?.form?.length)return 0;const pts=b.form.slice(-5).reduce((s,r)=>s+(r==='W'?3:r==='D'?1:0),0);return clamp((pts-7)/3,-2.2,2.2)}
function lineupPower(){try{if(!G.lineup?.length)return strength(G.club,G.division);const vals=G.lineup.map(n=>G.roster.find(p=>p[0]===n)?.[2]).filter(Number.isFinite);return vals.length>=7?avg(vals):strength(G.club,G.division)}catch{return strength(G.club,G.division)}}
function tac(){return Object.assign({style:'Equilibrado',mentality:'Equilibrada',pressing:'Média',tempo:'Normal',width:'Normal'},G.tactics||{})}
function tactical(team,isHome){if(team!==G.club)return {power:0,attack:1,defense:1,fatigue:1};const t=tac();let power=0,attack=1,defense=1,fatigue=1;
if(t.mentality==='Ofensiva'){power+=.6;attack*=1.16;defense*=1.10;fatigue*=1.05}else if(t.mentality==='Defensiva'){power-=.15;attack*=.84;defense*=.82;fatigue*=.96}
if(t.pressing==='Alta'){power+=.45;attack*=1.08;defense*=.91;fatigue*=1.11}else if(t.pressing==='Baixa'){attack*=.94;defense*=1.04;fatigue*=.94}
if(t.tempo==='Rápido'){attack*=1.10;defense*=1.04;fatigue*=1.08}else if(t.tempo==='Lento'){attack*=.91;defense*=.96;fatigue*=.95}
if(t.style==='Posse de bola'){power+=.35;attack*=.97;defense*=.93}else if(t.style==='Contra-ataque'){attack*=1.04;defense*=.95;if(!isHome)power+=.35}else if(t.style==='Jogo direto'){attack*=1.08;defense*=1.03;fatigue*=1.03}else if(t.style==='Pelas pontas'){attack*=1.05}
if(t.width==='Aberta'){attack*=1.04;defense*=1.04}else if(t.width==='Fechada'){attack*=.96;defense*=.93}
return {power,attack,defense,fatigue}}
function power(team,d,g){let p=team===G.club?lineupPower():strength(team,d);if(team===g.h)p+=1.8;if(team===G.club){p+=(clamp(G.confidence||68,35,90)-65)/9;p+=userFormBoost();p+=tactical(team,team===g.h).power;p+=(G.clubEvents?.moraleBoost||0)*.12}return p}
window.FGTacticsMatch={effects:()=>tactical(G.club,userGame?.()?.h===G.club),get:tac};
window.simulateGoal=function(d,g){if(g.played)return;if(g._swing==null)g._swing=(Math.random()+Math.random()+Math.random()-1.5)*5.2;let hp=power(g.h,d,g)+g._swing,ap=power(g.a,d,g)-g._swing;const diff=clamp((hp-ap)/14,-2.2,2.2);let hc=.034+diff*.0105,ac=.034-diff*.0105;const ht=tactical(g.h,true),at=tactical(g.a,false);hc*=ht.attack*at.defense;ac*=at.attack*ht.defense;if(g.hg>g.ag){hc*=.88;ac*=1.10}else if(g.ag>g.hg){ac*=.88;hc*=1.10}const total=g.hg+g.ag;if(total>=5){hc*=.72;ac*=.72}hc=clamp(hc,.007,.072);ac=clamp(ac,.007,.072);if(Math.random()<hc)g.hg++;if(Math.random()<ac)g.ag++};
function recordResult(){try{const g=userGame();if(!g||!g.played||g._recordedBalance)return;g._recordedBalance=true;const us=g.h===G.club?g.hg:g.ag,them=g.h===G.club?g.ag:g.hg,b=ensureMeta();b.form.push(us>them?'W':us===them?'D':'L');b.form=b.form.slice(-8);b.matches++;if(G.clubEvents?.moraleBoost)G.clubEvents.moraleBoost=Math.max(0,G.clubEvents.moraleBoost-1);const gd=us-them;if(gd>=3)addNews('Atuação de gala',`${G.club} venceu com autoridade. Moral do grupo em alta.`);if(gd<=-3)addNews('Noite para esquecer','Derrota pesada. O elenco vai precisar de resposta rápida.');saveGame(false)}catch(e){console.warn('balance record',e)}}
const oldRender=window.renderAll;if(typeof oldRender==='function')window.renderAll=function(){recordResult();oldRender();try{const g=userGame();if(g&&!g.played){const d=G.division,us=power(G.club,d,g),opp=g.h===G.club?g.a:g.h,op=power(opp,d,g),delta=us-op,tag=delta>7?'Tu chega como favorito':delta<-7?'Jogo bem complicado':Math.abs(delta)<3?'Confronto equilibrado':'Dá jogo';const el=document.getElementById('matchRound');if(el&&!el.textContent.includes('• '+tag))el.textContent+=' • '+tag}}catch{}};setTimeout(()=>{ensureMeta();if(typeof window.renderAll==='function')window.renderAll()},0);
})();