(()=>{
function init(){if(!window.G)return false;G.managerCareer=G.managerCareer||{status:'employed',reputation:50,history:[],offers:[],lastClub:G.club};G.managerCareer.offerYear=G.managerCareer.offerYear||null;return true}
function clubs(){let out=[];for(const d of ['B','A2','A1'])for(const c of(DIV[d]?.clubs||[]))if(c!==G.club)out.push({club:c,division:d});return out}
function gen(endSeason=false){if(!init())return;let rep=G.managerCareer.reputation||50,list=clubs().filter(x=>x.division==='B'||rep>=58&&x.division==='A2'||rep>=76&&x.division==='A1');list.sort(()=>Math.random()-.5);G.managerCareer.offers=list.slice(0,endSeason?4:3);if(endSeason)G.managerCareer.offerYear=G.year;saveGame(false);render()}
function seasonOffers(){if(!init()||G.managerCareer.status!=='employed'||!G.seasonEnded||!G.cup?.winner)return;if(G.managerCareer.offerYear===G.year)return;let chance=Math.min(.85,.25+(G.managerCareer.reputation||50)/120);G.managerCareer.offerYear=G.year;if(Math.random()<chance){gen(true);if(G.managerCareer.offers.length)addNews('Sondagens para o Professor',`${G.managerCareer.offers.length} clubes procuraram o Professor para a próxima temporada. Tu só sai do ${G.club} se aceitar uma proposta.`)}else{G.managerCareer.offers=[];saveGame(false)}render()}
function leave(reason){if(!init()||G.managerCareer.status==='unemployed')return;G.clubStates=G.clubStates||{};G.clubStates[G.club]={roster:structuredClone(G.roster),cash:G.cash,sponsor:G.sponsor,division:G.division};G.managerCareer.history.unshift({year:G.year,club:G.club,reason});G.managerCareer.lastClub=G.club;G.managerCareer.status='unemployed';G.managerCareer.offers=[];addNews('Professor sem clube',reason==='fired'?`A diretoria demitiu o Professor após a confiança chegar a ${G.confidence}%.`:`O Professor pediu demissão do ${G.club}.`);gen();toast(reason==='fired'?'Tu foi demitido. Hora de procurar outro clube.':'Pedido de demissão confirmado.');render()}
function resign(){if(confirm(`Pedir demissão do ${G.club}? O elenco e o dinheiro ficam no clube.`))leave('resigned')}
function accept(i){let o=G.managerCareer.offers[i];if(!o)return;let old=G.club;G.clubStates=G.clubStates||{};G.clubStates[old]={roster:structuredClone(G.roster),cash:G.cash,sponsor:G.sponsor,division:G.division};G.managerCareer.status='employed';G.club=o.club;G.division=o.division;let saved=G.clubStates[G.club],real=(G.db||[]).filter(p=>p.c===G.club);if(saved){G.roster=structuredClone(saved.roster);G.cash=saved.cash;G.sponsor=saved.sponsor||null}else{G.roster=real.length?real.map(p=>[p.n,p.p,p.ov]):makeGenericRoster(G.club,o.division);G.cash=o.division==='A1'?1500000:o.division==='A2'?650000:260000;G.sponsor=null}G.lineup=[];G.confidence=65;G.managerCareer.offers=[];G.managerCareer.history.unshift({year:G.year,club:G.club,reason:`aceitou proposta do ${G.club}`});addNews('Novo trabalho',`O Professor aceitou a proposta do ${G.club} e deixou o ${old}.`);saveGame(false);renderAll();render();toast(`Agora tu é Professor do ${G.club}!`)}
function declineAll(){if(!init())return;G.managerCareer.offers=[];addNews('Professor permanece',`O Professor recusou as propostas e continuará no ${G.club} na próxima temporada.`);saveGame(false);render();toast(`Tu permanece no ${G.club}.`)}
function makeGenericRoster(club,d){let pool=(G.db||[]).filter(p=>p.c===club);return pool.length?pool.map(p=>[p.n,p.p,p.ov]):[['Goleiro','GOL',45],['Lateral D','LD',45],['Zagueiro 1','ZAG',46],['Zagueiro 2','ZAG',45],['Lateral E','LE',44],['Volante','VOL',45],['Meia 1','MC',46],['Meia 2','MEI',47],['Ponta D','PD',46],['Ponta E','PE',45],['Centroavante','ATA',48],['Reserva 1','GOL',40],['Reserva 2','ZAG',41],['Reserva 3','MC',42],['Reserva 4','ATA',43]]}
function render(){if(!init())return;let box=document.getElementById('fgJobs');if(!box){let home=document.getElementById('homeNews')?.parentElement||document.getElementById('inboxList')?.parentElement;if(!home)return;box=document.createElement('div');box.id='fgJobs';box.className='panel';home.prepend(box)}let offers=G.managerCareer.offers||[];if(G.managerCareer.status==='employed'){box.innerHTML=`<h3>💼 Carreira do Professor</h3><div class=item><b>${G.club}</b> • confiança ${G.confidence}% • reputação ${G.managerCareer.reputation}<button class=btn onclick="FGJobs.resign()">Pedir demissão</button></div>${offers.length?`<h3>📨 Propostas para a próxima temporada</h3>${offers.map((o,i)=>`<div class=item><b>${o.club}</b> • ${DIV[o.division]?.name||o.division}<button class="btn green" onclick="FGJobs.accept(${i})">Aceitar proposta</button></div>`).join('')}<button class=btn onclick="FGJobs.declineAll()">Recusar todas e permanecer no ${G.club}</button>`:''}<div class=mut>Tu permanece no ${G.club} automaticamente se não aceitar proposta, não pedir demissão e não for demitido.</div>`}else box.innerHTML=`<h3>📨 Propostas de emprego</h3>${offers.map((o,i)=>`<div class=item><b>${o.club}</b> • ${DIV[o.division]?.name||o.division}<button class=btn onclick="FGJobs.accept(${i})">Aceitar proposta</button></div>`).join('')||'<div class=item>Nenhuma proposta agora.</div><button class=btn onclick="FGJobs.generate()">Procurar vagas</button>'}`}
function check(){if(!init())return;if(G.managerCareer.status==='employed'&&G.confidence<=33)leave('fired');seasonOffers();render()}
window.FGJobs={init,resign,accept,declineAll,generate:gen,seasonOffers,check};setTimeout(()=>{init();check()},1800);setInterval(check,2500)
})();