(()=>{
const CLUBS=['Internacional','Juventude','Avenida','São José','Guarany de Bagé','São Luiz','Grêmio','Caxias','Novo Hamburgo','Monsoon','Inter-SM','Ypiranga','Aimoré','APAFUT','Bagé','Brasil-FAR','Brasil-Pel','Esportivo','Gaúcho','Glória','Gramadense','Guarani-VA','Lajeadense','Passo Fundo','Pelotas','Santa Cruz','União Frederiquense','Veranópolis','Clube 1992','Cruz Alta','Farroupilha','Futebol Com Vida','Novo Horizonte','Panambi','Real Sport','Rio Grande','Riograndense-RG','São Paulo-RG'];
const COLORS={'Internacional':['#c00','#fff'],'Grêmio':['#159bd7','#111'],'Juventude':['#16843b','#fff'],'Caxias':['#7d111c','#fff'],'Brasil-Pel':['#c71920','#111'],'Pelotas':['#f5c400','#1763a6'],'São José':['#174ea6','#fff'],'Ypiranga':['#13823b','#f5c400'],'Novo Hamburgo':['#1b63a8','#fff'],'São Luiz':['#d71920','#fff'],'Avenida':['#16763b','#fff'],'Inter-SM':['#d71920','#fff'],'Guarany de Bagé':['#d71920','#fff'],'Monsoon':['#111','#f5c400'],'Aimoré':['#174ea6','#fff'],'Bagé':['#f0c400','#111'],'Esportivo':['#174ea6','#fff'],'Gaúcho':['#16843b','#fff'],'Glória':['#174ea6','#fff'],'Gramadense':['#174ea6','#d71920'],'Guarani-VA':['#d71920','#fff'],'Lajeadense':['#174ea6','#fff'],'Passo Fundo':['#d71920','#16843b'],'Santa Cruz':['#111','#fff'],'Veranópolis':['#d71920','#fff'],'Farroupilha':['#d71920','#16843b'],'Rio Grande':['#f0c400','#16843b'],'São Paulo-RG':['#d71920','#16843b']};
const initials=n=>n.split(/[ -]/).filter(x=>x.length>2||/^FC|SC|GE$/i.test(x)).slice(0,2).map(x=>x[0]).join('').toUpperCase()||n.slice(0,2).toUpperCase();
function fallback(n,size=28){const c=COLORS[n]||['#d8a52b','#17271c'];const t=initials(n);return `<span class="fgCrest" title="${n}" style="--c1:${c[0]};--c2:${c[1]};width:${size}px;height:${size}px"><b>${t}</b></span>`}
window.clubCrest=(n,size=28)=>fallback(n,size);
function injectStyle(){const s=document.createElement('style');s.textContent='.fgCrest{display:inline-grid;place-items:center;flex:0 0 auto;border-radius:50% 50% 45% 45%;background:linear-gradient(135deg,var(--c1) 0 52%,var(--c2) 53%);border:2px solid #ffffffcc;box-shadow:0 1px 5px #0008;vertical-align:middle;margin:0 6px}.fgCrest b{font:800 9px system-ui;color:#fff;text-shadow:0 1px 3px #000,0 0 2px #000}.clubWithCrest{display:inline-flex;align-items:center;gap:3px}';document.head.appendChild(s)}
function decorate(){try{const names=[...(window.DIV?Object.values(DIV).flatMap(d=>d.clubs):CLUBS)].sort((a,b)=>b.length-a.length);document.querySelectorAll('.item,.liveGame,td,#nextGame,#matchTitle').forEach(el=>{if(el.dataset.crests==='1')return;let h=el.innerHTML;let changed=false;for(const n of names){if(!n||!h.includes(n)||h.includes('title="'+n+'"'))continue;const esc=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');h=h.replace(new RegExp('(?<![\w>])'+esc+'(?![\w<])','g'),m=>{changed=true;return `<span class="clubWithCrest">${fallback(n,24)}<span>${m}</span></span>`})}if(changed){el.innerHTML=h;el.dataset.crests='1'}})}catch(e){console.warn('crests',e)}}
injectStyle();setTimeout(decorate,150);const mo=new MutationObserver(()=>{clearTimeout(window.__crestT);window.__crestT=setTimeout(decorate,80)});setTimeout(()=>mo.observe(document.body,{childList:true,subtree:true}),200);
window.FGClubLogos={clubs:CLUBS,decorate};
})();