(()=>{
const CLUBS=['Internacional','Juventude','Avenida','São José','Guarany de Bagé','São Luiz','Grêmio','Caxias','Novo Hamburgo','Monsoon','Inter-SM','Ypiranga','Aimoré','APAFUT','Bagé','Brasil-FAR','Brasil-Pel','Esportivo','Gaúcho','Glória','Gramadense','Guarani-VA','Lajeadense','Passo Fundo','Pelotas','Santa Cruz','União Frederiquense','Veranópolis','Clube 1992','Cruz Alta','Farroupilha','Futebol Com Vida','Novo Horizonte','Panambi','Real Sport','Rio Grande','Riograndense-RG','São Paulo-RG'];
const LOGOS={
'Internacional':'https://escudosfc.com.br/images/interrs.png','Juventude':'https://escudosfc.com.br/images/juventude.png','Avenida':'https://escudosfc.com.br/images/avenida_rs.png','São José':'https://escudosfc.com.br/images/saojose_rs.png','Guarany de Bagé':'https://escudosfc.com.br/images/gbage_rs.jpg','São Luiz':'https://escudosfc.com.br/images/saoluiz_rs.png','Grêmio':'https://escudosfc.com.br/images/gremio.png','Caxias':'https://escudosfc.com.br/images/caxias.gif','Novo Hamburgo':'https://escudosfc.com.br/images/novohamburgo.png','Monsoon':'https://escudosfc.com.br/images/monsoon_rs.jpg','Inter-SM':'https://escudosfc.com.br/images/inter_sm_rs.jpg','Ypiranga':'https://escudosfc.com.br/images/ypiranga_rs.png',
'Aimoré':'https://escudosfc.com.br/images/aimore_rs.png','APAFUT':'https://escudosfc.com.br/images/apafut_rs.png','Bagé':'https://escudosfc.com.br/images/bage.png','Brasil-FAR':'https://escudosfc.com.br/images/brasil_f_rs.jpg','Brasil-Pel':'https://escudosfc.com.br/images/gebrasil.gif','Esportivo':'https://escudosfc.com.br/images/esportivo_rs.png','Gaúcho':'https://escudosfc.com.br/images/gaucho.png','Glória':'https://escudosfc.com.br/images/gloria_rs.png','Gramadense':'https://escudosfc.com.br/images/gramadense_rs.png','Guarani-VA':'https://escudosfc.com.br/images/guaranivaires_rs.png','Lajeadense':'https://escudosfc.com.br/images/lajeadense_rs.jpg','Passo Fundo':'https://escudosfc.com.br/images/passofundo.jpg','Pelotas':'https://escudosfc.com.br/images/pelotas.jpg','Santa Cruz':'https://escudosfc.com.br/images/santacruz_rs.jpg','União Frederiquense':'https://escudosfc.com.br/images/uniao_fred_rs.png','Veranópolis':'https://escudosfc.com.br/images/veranopolis_rs.png',
'Clube 1992':'https://escudosfc.com.br/images/rs_1992.png','Cruz Alta':'https://escudosfc.com.br/images/cruz_alta_rs.png','Farroupilha':'https://escudosfc.com.br/images/farroupilha.gif','Futebol Com Vida':'https://escudosfc.com.br/images/fut_com_vida_rs.jpg','Novo Horizonte':'https://escudosfc.com.br/images/novo_horizonte_rs.png','Panambi':'https://escudosfc.com.br/images/panambi_rs.gif','Real Sport':'https://escudosdefutbolyequipaciones.com/images_esc3/CONM/BRASIL/escudos_jpg/escudo-real%20sport%20club.jpg','Rio Grande':'https://escudosfc.com.br/images/riogrande.jpg','Riograndense-RG':'https://escudosfc.com.br/images/riograndense_fb.jpg','São Paulo-RG':'https://escudosfc.com.br/images/saopaulo_rs.gif'};
const COLORS={'Internacional':['#c00','#fff'],'Grêmio':['#159bd7','#111'],'Juventude':['#16843b','#fff'],'Caxias':['#7d111c','#fff'],'Brasil-Pel':['#c71920','#111'],'Pelotas':['#f5c400','#1763a6'],'São José':['#174ea6','#fff'],'Ypiranga':['#13823b','#f5c400'],'Novo Hamburgo':['#1b63a8','#fff'],'São Luiz':['#d71920','#fff'],'Avenida':['#16763b','#fff'],'Inter-SM':['#d71920','#fff'],'Guarany de Bagé':['#d71920','#fff'],'Monsoon':['#111','#f5c400']};
const initials=n=>n.split(/[ -]/).filter(x=>x.length>2||/^FC|SC|GE$/i.test(x)).slice(0,2).map(x=>x[0]).join('').toUpperCase()||n.slice(0,2).toUpperCase();
function fallback(n,size=28){const c=COLORS[n]||['#d8a52b','#17271c'];return `<span class="fgCrestFallback" title="${n}" style="--c1:${c[0]};--c2:${c[1]};width:${size}px;height:${size}px"><b>${initials(n)}</b></span>`}
function crest(n,size=28){const src=LOGOS[n];if(!src)return fallback(n,size);return `<span class="fgCrestWrap" title="${n}" style="width:${size}px;height:${size}px"><img class="fgCrestImg" src="${src}" alt="Escudo ${n}" loading="lazy" onerror="this.parentElement.outerHTML=window.__fgFallback('${n.replace(/'/g,"\\'")}',${size})"></span>`}
window.__fgFallback=fallback;window.clubCrest=crest;
function injectStyle(){const s=document.createElement('style');s.textContent='.fgCrestWrap{display:inline-grid;place-items:center;flex:0 0 auto;vertical-align:middle;margin:0 5px}.fgCrestImg{display:block;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 1px 2px #0008)}.fgCrestFallback{display:inline-grid;place-items:center;flex:0 0 auto;border-radius:50% 50% 45% 45%;background:linear-gradient(135deg,var(--c1) 0 52%,var(--c2) 53%);border:2px solid #ffffffcc;vertical-align:middle;margin:0 5px}.fgCrestFallback b{font:800 9px system-ui;color:#fff;text-shadow:0 1px 3px #000}.clubWithCrest{display:inline-flex;align-items:center;gap:3px}';document.head.appendChild(s)}
function decorate(){try{const names=[...(window.DIV?Object.values(DIV).flatMap(d=>d.clubs):CLUBS)].sort((a,b)=>b.length-a.length);document.querySelectorAll('.item,.liveGame,td,#nextGame,#matchTitle,#calendarList,#cupList').forEach(el=>{if(el.dataset.crests==='1')return;let h=el.innerHTML,changed=false;for(const n of names){if(!n||!h.includes(n)||h.includes('title="'+n+'"'))continue;const esc=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');h=h.replace(new RegExp('(?<![\\w>])'+esc+'(?![\\w<])','g'),m=>{changed=true;return `<span class="clubWithCrest">${crest(n,24)}<span>${m}</span></span>`})}if(changed){el.innerHTML=h;el.dataset.crests='1'}})}catch(e){console.warn('crests',e)}}
injectStyle();setTimeout(decorate,150);const mo=new MutationObserver(()=>{clearTimeout(window.__crestT);window.__crestT=setTimeout(decorate,80)});setTimeout(()=>mo.observe(document.body,{childList:true,subtree:true}),200);window.FGClubLogos={clubs:CLUBS,logos:LOGOS,decorate};
})();