(()=>{
let LIVE=null;
function sh(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function strength(c){try{return Number(clubStrength(c)||50)}catch(e){return 50}}
function blank(t){return{t,J:0,V:0,E:0,D:0,GP:0,GC:0,SG:0,P:0}}
function setup(){let seeds=sh([...new Set(DIV.A1.clubs)]),others=sh([...new Set([...DIV.A2.clubs,...DIV.B.clubs].filter(x=>!seeds.includes(x)))]);if(!seeds.includes(G.club)&&!others.includes(G.club))others.push(G.club);let total=seeds.length+others.length,groupCount=Math.floor(total/4);while(seeds.length>groupCount)others.push(seeds.pop());let groups=[];for(let i=0;i<groupCount;i++){let teams=[];if(seeds[i])teams.push(seeds[i]);while(teams.length<4&&others.length)teams.push(others.shift());if(teams.length<4)break;let games=[];for(let a=0;a<4;a++)for(let b=a+1;b<4;b++)games.push({h:teams[a],a:teams[b],played:false,hg:0,ag:0});groups.push({name:String.fromCharCode(65+groups.length),teams,seed:teams[0],table:Object.fromEntries(teams.map(t=>[t,blank(t)])),games})}G.cup={format:'groups4-live-v4',stage:'groups',groupRound:0,groups,qualified:[],ko:[],winner:null,log:[],gauchoChamp:G.playoffs?.A1?.winner||null};G.phase='cup';G.seasonEnded=true;saveGame(false)}
function apply(g,t){let H=t[g.h],A=t[g.a];if(!H||!A)return;H.J++;A.J++;H.GP+=g.hg;H.GC+=g.ag;A.GP+=g.ag;A.GC+=g.hg;H.SG=H.GP-H.GC;A.SG=A.GP-A.GC;if(g.hg>g.ag){H.V++;A.D++;H.P+=3}else if(g.hg<g.ag){A.V++;H.D++;A.P+=3}else{H.E++;A.E++;H.P++;A.P++}}
function sorted(gr){return Object.values(gr.table).sort((a,b)=>b.P-a.P||b.V-a.V||b.SG-a.SG||b.GP-a.GP)}
function pairsFor(r){return r===0?[[0,3],[1,2]]:r===1?[[0,2],[3,1]]:[[0,1],[2,3]]}
function roundGames(){let r=G.cup.groupRound,out=[];for(const gr of G.cup.groups){for(const[i,j]of pairsFor(r)){let h=gr.teams[i],a=gr.teams[j],g=gr.games.find(x=>(x.h===h&&x.a===a)||(x.h===a&&x.a===h));if(g&&!g.played)out.push({g,gr})}}return out}
function goalChance(g,minute){let sa=strength(g.h),sb=strength(g.a),base=.105;if(minute>70)base+=.018;let hChance=Math.max(.18,Math.min(.82,.5+(sa-sb)/150));if(Math.random()<base){if(Math.random()<hChance)g.hg++;else g.ag++;return true}return false}
function teamCrest(n,s=34){try{return window.clubCrest?clubCrest(n,s):''}catch(e){return''}}
function liveRows(){if(!LIVE)return'';return LIVE.games.map(({g,gr})=>`<div class="fgCupLiveRow"><span class="fgCupGrp">${gr?gr.name:'KO'}</span><span>${teamCrest(g.h,24)}${g.h}</span><b>${g.hg} x ${g.ag}</b><span>${teamCrest(g.a,24)}${g.a}</span></div>`).join('')}
function liveRender(){if(!LIVE)return;let sc=document.getElementById('fgCupScore'),other=document.getElementById('fgCupOther'),clock=document.getElementById('fgCupClock');if(clock)clock.textContent=LIVE.minute+"'";if(sc&&LIVE.user)sc.innerHTML=`<div class="fgCupTeam">${teamCrest(LIVE.user.g.h,54)}<b>${LIVE.user.g.h}</b></div><div class="fgCupBig">${LIVE.user.g.hg} <span>x</span> ${LIVE.user.g.ag}</div><div class="fgCupTeam">${teamCrest(LIVE.user.g.a,54)}<b>${LIVE.user.g.a}</b></div>`;if(other)other.innerHTML=liveRows()}
function addLiveLog(text,hot=false){let el=document.getElementById('fgCupFeed');if(el)el.innerHTML=`<div class="item${hot?' fgCupGoal':''}">${text}</div>`+el.innerHTML}
function finishLive(){if(!LIVE)return;clearInterval(LIVE.timer);LIVE.timer=null;for(const x of LIVE.games){x.g.played=true;if(x.gr)apply(x.g,x.gr.table);G.cup.log.unshift(`${x.gr?'Grupo '+x.gr.name:'Mata-mata'}: ${x.g.h} ${x.g.hg} x ${x.g.ag} ${x.g.a}`)}if(G.cup.stage==='groups')G.cup.groupRound++;saveGame(false);let btn=document.getElementById('fgCupAction');if(btn){btn.disabled=false;btn.textContent='CONTINUAR NA COPINHA';btn.onclick=closeLive}let title=document.getElementById('fgCupStatus');if(title)title.textContent='Fim de jogo';addLiveLog(`90' • FIM DE JOGO`,true);LIVE.finished=true}
function closeLive(){let m=document.getElementById('fgCupLive');if(m)m.remove();let needFinish=G.cup.stage==='groups'&&G.cup.groupRound>=3;LIVE=null;if(needFinish)finishGroups();else renderCup()}
function tick(){if(!LIVE||LIVE.paused||LIVE.finished)return;LIVE.minute=Math.min(90,LIVE.minute+3);for(const x of LIVE.games){let before=x.g.hg+x.g.ag;if(goalChance(x.g,LIVE.minute)){let scorer=x.g.hg+x.g.ag>before?(Math.random()<.5?x.g.h:x.g.a):'';if(x===LIVE.user||x.g.h===G.club||x.g.a===G.club)addLiveLog(`${LIVE.minute}' ⚽ GOL! ${x.g.h} ${x.g.hg} x ${x.g.ag} ${x.g.a}`,true)}}if(LIVE.user&&Math.random()<.18)addLiveLog(`${LIVE.minute}' • ${Math.random()<.5?LIVE.user.g.h:LIVE.user.g.a} chega ao ataque.`);liveRender();if(LIVE.minute===45&&!LIVE.halfDone){LIVE.paused=true;LIVE.halfDone=true;let btn=document.getElementById('fgCupAction');if(btn){btn.disabled=false;btn.textContent='▶ COMEÇAR 2º TEMPO';btn.onclick=()=>{LIVE.paused=false;btn.disabled=true;btn.textContent='JOGO EM ANDAMENTO...';addLiveLog(`46' • Começa o segundo tempo.`)}}let st=document.getElementById('fgCupStatus');if(st)st.textContent='Intervalo'}else if(LIVE.minute>=90)finishLive()}
function openLive(games){let user=games.find(x=>x.g.h===G.club||x.g.a===G.club)||null;let old=document.getElementById('fgCupLive');if(old)old.remove();let m=document.createElement('div');m.id='fgCupLive';m.innerHTML=`<style>#fgCupLive{position:fixed;inset:0;background:#020504f2;z-index:100000;overflow:auto;padding:18px}.fgCupBox{max-width:1050px;margin:auto;background:#0c140f;border:1px solid #314b39;border-radius:18px;padding:18px}.fgCupHead{display:flex;justify-content:space-between;gap:12px;align-items:center}.fgCupClock{font-size:30px;font-weight:1000;color:#d8a52b}.fgCupScore{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px;margin:22px 0;padding:18px;background:#101d15;border-radius:16px}.fgCupTeam{display:flex;align-items:center;justify-content:center;gap:8px;font-size:20px;text-align:center}.fgCupBig{font-size:46px;font-weight:1000;white-space:nowrap}.fgCupBig span{color:#829184;font-size:24px}.fgCupGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fgCupLiveRow{display:grid;grid-template-columns:34px 1fr 70px 1fr;gap:7px;align-items:center;padding:7px;border-bottom:1px solid #ffffff10}.fgCupGrp{font-weight:900;color:#d8a52b}.fgCupGoal{color:#6df08f;font-weight:900}@media(max-width:760px){.fgCupGrid{grid-template-columns:1fr}.fgCupScore{grid-template-columns:1fr;gap:7px}.fgCupBig{font-size:38px}.fgCupLiveRow{grid-template-columns:28px 1fr 55px 1fr;font-size:12px}}</style><div class="fgCupBox"><div class="fgCupHead"><div><h2 style="margin:0">🏆 COPINHA GAÚCHA • RODADA ${G.cup.groupRound+1}</h2><div id="fgCupStatus" class="mut">Bola rolando</div></div><div id="fgCupClock" class="fgCupClock">0'</div></div>${user?`<div id="fgCupScore" class="fgCupScore"></div>`:`<div class="card">Teu clube não joga nesta rodada. Acompanhe os resultados ao vivo.</div>`}<div class="fgCupGrid"><div><h3>Resultados ao vivo</h3><div id="fgCupOther" class="list"></div></div><div><h3>Lances</h3><div id="fgCupFeed" class="list" style="max-height:360px;overflow:auto"></div></div></div><button id="fgCupAction" class="btn green" disabled style="margin-top:14px;width:100%">JOGO EM ANDAMENTO...</button></div>`;document.body.appendChild(m);LIVE={games,user,minute:0,paused:false,halfDone:false,finished:false,timer:null};liveRender();addLiveLog(`0' • Começa a rodada da Copinha.`);LIVE.timer=setInterval(tick,310)}
function groupRound(){if(G.cup.groupRound>=3)return finishGroups();let games=roundGames();if(!games.length)return toast('Não há jogos pendentes nesta rodada.');openLive(games)}
function finishGroups(){if(G.cup.stage!=='groups')return;let q=[];for(const gr of G.cup.groups)q.push(...sorted(gr).slice(0,2).map(x=>x.t));G.cup.qualified=q;G.cup.stage='knockout';makeKO(q);addNews('Copinha Gaúcha','Fase de grupos encerrada. Os dois melhores de cada chave avançaram ao mata-mata.');saveGame(false);renderCup()}
function makeKO(teams){teams=sh(teams);G.cup.ko=[];for(let i=0;i<teams.length;i+=2)if(teams[i+1])G.cup.ko.push({h:teams[i],a:teams[i+1],played:false,hg:0,ag:0})}
function koRound(){let games=G.cup.ko.map(g=>({g,gr:null}));let user=games.find(x=>x.g.h===G.club||x.g.a===G.club);if(user){openKOLive(games);return}finishKOSim(games)}
function openKOLive(games){openLive(games);let h=document.querySelector('#fgCupLive h2');if(h)h.textContent=`🏆 COPINHA GAÚCHA • MATA-MATA`;let originalFinish=finishLive;window.__fgKoWatch=setInterval(()=>{if(LIVE?.finished){clearInterval(window.__fgKoWatch);let btn=document.getElementById('fgCupAction');if(btn)btn.onclick=()=>{resolveKO(games);document.getElementById('fgCupLive')?.remove();LIVE=null;renderCup()}}},120)}
function finishKOSim(games){for(const x of games){while(x.g.hg===x.g.ag){x.g.hg=Math.floor(Math.random()*3);x.g.ag=Math.floor(Math.random()*3)}x.g.played=true}resolveKO(games);renderCup()}
function resolveKO(games){let winners=[];for(const x of games){let g=x.g;if(g.hg===g.ag){if(Math.random()<strength(g.h)/(strength(g.h)+strength(g.a)))g.hg++;else g.ag++}let w=g.hg>g.ag?g.h:g.a;winners.push(w);G.cup.log.unshift(`${games.length===1?'FINAL':'Mata-mata'}: ${g.h} ${g.hg} x ${g.ag} ${g.a} — ${w} classificado`)}if(winners.length===1){G.cup.winner=winners[0];G.cup.stage='done';addNews('Campeão da Copinha',`${winners[0]} conquistou a Copinha Gaúcha ${G.year}.`);renderHistory?.()}else makeKO(winners);saveGame(false)}
function play(){if(!G.cup||!String(G.cup.format).startsWith('groups4-'))setup();if(G.cup.winner)return toast('A Copinha já terminou.');G.cup.stage==='groups'?groupRound():koRound()}
function renderCup(){let info=document.getElementById('cupInfo'),list=document.getElementById('cupList');if(!info||!list)return;if(!G.cup||!String(G.cup.format).startsWith('groups4-')){info.innerHTML='<p>A Copinha Gaúcha começa depois dos estaduais. Grupos de 4, rodada por rodada, com partidas acompanhadas durante os 90 minutos.</p><button class="btn green" onclick="FGCopinha.start()">INICIAR COPINHA</button>';list.innerHTML='';return}let c=G.cup;if(c.winner)info.innerHTML=`<p><b>🏆 Campeão da Copinha:</b> ${c.winner}</p>`;else info.innerHTML=`<p><b>${c.stage==='groups'?`Fase de grupos • rodada ${Math.min(c.groupRound+1,3)}/3`:`Mata-mata • ${c.ko.length*2} clubes`}</b><br>Grupos de 4 • 2 classificados • rodada por rodada • jogos em 90 minutos.</p><button class="btn green" onclick="FGCopinha.play()">${c.stage==='groups'?`▶ JOGAR RODADA ${c.groupRound+1}`:'▶ JOGAR MATA-MATA'}</button>`;let html='';for(const gr of c.groups){html+=`<div class="item"><b>GRUPO ${gr.name}</b> <span class="badge">⭐ CABEÇA: ${gr.seed}</span>${sorted(gr).map((x,i)=>`<div style="padding:5px 0;${i<2?'color:#69e58d;font-weight:700':''}">${i+1}º ${x.t} — ${x.P} pts • J ${x.J} • V ${x.V} • E ${x.E} • D ${x.D} • SG ${x.SG}</div>`).join('')}</div>`}if(c.stage==='knockout')html+=`<div class="item"><b>PRÓXIMOS JOGOS — MATA-MATA</b>${c.ko.map(g=>`<div style="padding:5px 0">${g.h} x ${g.a}</div>`).join('')}</div>`;if(c.log.length)html+=`<div class="item"><b>ÚLTIMOS RESULTADOS</b></div>`+c.log.slice(0,18).map(x=>`<div class="item">${x}</div>`).join('');list.innerHTML=html;setTimeout(()=>window.FGClubLogos?.decorate(),50)}
function start(){setup();renderCup()}
function repair(){if(!window.G)return;if(G.phase==='cup'&&G.cup&&G.cup.format==='groups4-seeded-v3')G.cup.format='groups4-live-v4';window.playCup=play;window.renderCup=renderCup}
window.FGCopinha={start,play,render:renderCup,repair,closeLive};setTimeout(()=>{repair();renderCup()},1800);setInterval(repair,1500)
})();