(()=>{
const FORM={'4-4-2':['GOL','LD','ZAG','ZAG','LE','PD','MC','MC','PE','ATA','ATA'],'4-3-3':['GOL','LD','ZAG','ZAG','LE','MC','VOL','MC','PD','ATA','PE'],'4-2-3-1':['GOL','LD','ZAG','ZAG','LE','VOL','VOL','PD','MEI','PE','ATA'],'3-5-2':['GOL','ZAG','ZAG','ZAG','LD','MC','VOL','MC','LE','ATA','ATA'],'4-1-4-1':['GOL','LD','ZAG','ZAG','LE','VOL','PD','MC','MC','PE','ATA']};
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function seed(){window.FGRealRosters?.apply();if(!G.db?.length&&window.FGRealRosters?.apply)FGRealRosters.apply()}
function market(){seed();const el=document.getElementById('marketList');if(!el)return;let q=norm(document.getElementById('marketQ')?.value),pool=(G.db||[]).filter(p=>p.c!==G.club);if(q)pool=pool.filter(p=>norm(`${p.n} ${p.c} ${p.p}`).includes(q));pool.sort((a,b)=>(b.real?1:0)-(a.real?1:0)||b.ov-a.ov);el.innerHTML=`<div class=bfHead><b>JOGADORES DA LIGA</b><span>${pool.length} encontrados</span></div>`+pool.slice(0,300).map(p=>`<div class=bfRow><div class=bfPos>${p.p}</div><div class=bfPlayer><b>${p.num?`#${p.num} `:''}${p.n}</b><small>${p.c}${p.real?' • elenco real':' • jogador da liga'}</small></div><div><b>${p.ov}</b><small>força</small></div><div><b>${fmt(p.value||0)}</b><small>valor</small></div><button class=btn onclick="${p.real||p.generated?`FGWorld.negotiate('${p.id}')`:`buyPlayer('${p.id}')`}">Negociar</button></div>`).join('')||'<div class=item>Nenhum jogador encontrado.</div>';const input=document.getElementById('marketQ');if(input&&!input.__bf){input.__bf=1;input.placeholder='Buscar jogador, clube ou posição...';input.addEventListener('input',market)}}
function lineup(){if(!G?.roster)return;const pitch=document.getElementById('pitch'),bench=document.getElementById('bench');if(!pitch||!bench)return;const formation=document.getElementById('formation')?.value||'4-4-2',slots=FORM[formation]||FORM['4-4-2'];if(!G.lineup||G.lineup.length!==11)G.lineup=G.roster.slice(0,11).map(p=>p[0]);const find=n=>G.roster.find(p=>p[0]===n);pitch.className='bfLineup';pitch.innerHTML=`<div class=bfLineHead><b>ESCALAÇÃO • ${formation}</b><button class=btn onclick="FGLineup?.autoPick?.()">Melhor XI</button></div><div class=bfXI>${slots.map((pos,i)=>{let p=find(G.lineup[i]);return `<button class=bfSlot data-i=${i} onclick="FGManagerUI.pick(${i})"><span>${pos}</span><b>${p?.[0]||'Escolher jogador'}</b><small>${p?`${p[1]} • ${p[2]}`:''}</small></button>`}).join('')}</div>`;const starters=new Set(G.lineup);bench.innerHTML='<div class=bfHead><b>BANCO / ELENCO</b><span>Clica no jogador para trocar</span></div>'+G.roster.filter(p=>!starters.has(p[0])).map(p=>`<button class=bfReserve onclick="FGManagerUI.reserve('${p[0].replace(/'/g,"\\'")}')"><b>${p[0]}</b><span>${p[1]}</span><strong>${p[2]}</strong></button>`).join('');window.__fgPick=null}
function pick(i){window.__fgPick=i;document.querySelectorAll('.bfSlot').forEach(x=>x.classList.toggle('sel',+x.dataset.i===i));toast('Agora escolhe um jogador do banco.')}
function reserve(n){if(window.__fgPick==null)return toast('Primeiro clica no titular que quer trocar.');let i=window.__fgPick,old=G.lineup[i],from=G.lineup.indexOf(n);if(from>=0)G.lineup[from]=old;G.lineup[i]=n;saveGame(false);lineup();toast(`${n} entrou no time.`)}
function calendar(){let host=document.getElementById('fgCalendar');if(!host)return;const months=['Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],mi=G.calendar?.monthIndex||0;let games=[];for(let r=0;r<(G.schedules?.[G.division]?.length||0);r++){let g=(G.schedules[G.division][r]||[]).find(x=>x.h===G.club||x.a===G.club);if(g)games.push({r,g})}host.innerHTML=`<div class=bfCalTop><button onclick="FGManagerUI.month(-1)">◀</button><b>📅 ${months[mi]||'Dezembro'} ${G.year}</b><button onclick="FGManagerUI.month(1)">▶</button></div><div class=bfCalGames>${games.slice(mi*4,mi*4+4).map((x,j)=>`<div><b>${String(mi*4+j+1).padStart(2,'0')}/${String(mi+3).padStart(2,'0')}</b><span>${x.g.h} × ${x.g.a}</span><strong>${x.g.played?`${x.g.hg} - ${x.g.ag}`:'A disputar'}</strong></div>`).join('')||'<div>Sem jogos neste mês.</div>'}</div>`}
function month(d){G.calendar=G.calendar||{monthIndex:0};G.calendar.monthIndex=Math.max(0,Math.min(9,(G.calendar.monthIndex||0)+d));calendar()}
function boot(){if(!window.G)return;seed();window.renderMarket=market;window.renderLineup=lineup;setTimeout(()=>{market();lineup();calendar()},300)}
window.FGManagerUI={market,lineup,pick,reserve,calendar,month};const st=document.createElement('style');st.textContent=`.bfHead,.bfLineHead{display:flex;justify-content:space-between;align-items:center;padding:10px 12px;background:#171d18;border-bottom:2px solid #d8a52b}.bfRow{display:grid;grid-template-columns:58px minmax(180px,1fr) 70px 125px 100px;gap:10px;align-items:center;padding:10px;border-bottom:1px solid #273129}.bfRow small,.bfPlayer small{display:block;color:#93a097;font-size:11px}.bfPos{font-weight:900;color:#d8a52b}.bfLineup{background:#0b120d!important;border:1px solid #3a473d!important;border-radius:10px!important;padding:0!important;min-height:0!important;width:100%!important}.bfXI{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;padding:10px}.bfSlot,.bfReserve{border:1px solid #34443a;background:#142019;color:#fff;border-radius:7px;padding:9px;text-align:left;cursor:pointer}.bfSlot span{display:inline-block;background:#d8a52b;color:#171004;padding:2px 6px;border-radius:4px;font-weight:900;font-size:10px;margin-right:7px}.bfSlot b{font-size:13px}.bfSlot small{display:block;color:#94a098;margin-top:4px}.bfSlot.sel{outline:2px solid #d8a52b;background:#26301e}.bfReserve{display:grid;width:100%;grid-template-columns:1fr 55px 40px;gap:8px;margin:5px 0}.bfReserve span{color:#aab3ac}.bfReserve strong{color:#d8a52b}.bfCalTop{display:flex;justify-content:space-between;align-items:center;padding:10px;background:#171d18}.bfCalTop button{background:#d8a52b;border:0;border-radius:5px;padding:6px 12px;font-weight:900}.bfCalGames>div{display:grid;grid-template-columns:70px 1fr 90px;gap:10px;padding:9px;border-bottom:1px solid #28332b}.bfCalGames strong{text-align:right}@media(max-width:650px){.bfRow{grid-template-columns:45px 1fr 45px}.bfRow>div:nth-of-type(4){display:none}.bfRow .btn{grid-column:2/4}.bfXI{grid-template-columns:1fr}}`;document.head.appendChild(st);setTimeout(boot,1500);setInterval(()=>{if(window.G&&!window.__fgManagerReady){window.__fgManagerReady=1;boot()}},1000)
})();