(()=>{
const FORM={'4-4-2':['GOL','LD','ZAG','ZAG','LE','PD','MC','MC','PE','ATA','ATA'],'4-3-3':['GOL','LD','ZAG','ZAG','LE','MC','VOL','MC','PD','ATA','PE'],'4-2-3-1':['GOL','LD','ZAG','ZAG','LE','VOL','VOL','PD','MEI','PE','ATA'],'3-5-2':['GOL','ZAG','ZAG','ZAG','LD','MC','VOL','MC','LE','ATA','ATA'],'4-1-4-1':['GOL','LD','ZAG','ZAG','LE','VOL','PD','MC','MC','PE','ATA']};
const REAL=['Internacional','Grêmio','Juventude','Caxias','Brasil-Pel','Pelotas','Aimoré','Passo Fundo','Ypiranga'];const RD={Internacional:'A1','Grêmio':'A1',Juventude:'A1',Caxias:'A1',Ypiranga:'A1','Brasil-Pel':'A2',Pelotas:'A2',Aimoré:'A2','Passo Fundo':'A2'};
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let selected=null;
function sync(){if(!window.G||!window.FGRealRosters)return;G.db=G.db||[];G.db=G.db.filter(p=>!REAL.includes(p.c));for(const club of REAL){const rows=FGRealRosters.rosters?.[club]||[];rows.forEach((r,i)=>{let n,p,num,ov;if(Array.isArray(r))[n,p,num,ov]=r;else({n,p,num,ov}=r);let d=RD[club],value=FGRealRosters.value(ov,d);G.db.push({id:`REAL-${norm(club).replace(/[^a-z0-9]/g,'')}-${i}`,n,p,num,ov,c:club,d,value,real:true})})}FGRealGuard?.clean?.()}
function market(){sync();const el=document.getElementById('marketList'),inp=document.getElementById('marketQ');if(!el||!inp)return;let q=norm(inp.value),pool=(G.db||[]).filter(p=>p.c!==G.club);if(q)pool=pool.filter(p=>norm(`${p.n} ${p.c} ${p.p}`).includes(q));pool.sort((a,b)=>(b.real===true)-(a.real===true)||b.ov-a.ov);el.innerHTML=`<div class=bfTitle><b>MERCADO DE JOGADORES</b><span>${pool.length} resultado(s)</span></div>${pool.slice(0,500).map(p=>`<div class=bfMarket><b>${p.num?`#${p.num} `:''}${p.n}</b><span>${p.p}</span><span>${p.c}</span><strong>${p.ov}</strong><span>${fmt(p.value||0)}</span><button class=btn onclick="FGManagerUI.player('${p.id}')">Ver</button><button class=btn onclick="FGManagerUI.offer('${p.id}')">Proposta</button></div>`).join('')||'<div class=item>Nenhum jogador encontrado.</div>'}`;if(!inp.__live){inp.__live=1;inp.placeholder='Digite nome, clube ou posição';inp.oninput=market}}
function player(id){let p=G.db.find(x=>x.id===id);if(p)alert(`${p.n}\nClube: ${p.c}\nPosição: ${p.p}\nForça: ${p.ov}\nValor: ${fmt(p.value||0)}${p.num?`\nCamisa: ${p.num}`:''}`)}
function offer(id){let p=G.db.find(x=>x.id===id);if(!p)return;if(window.FGWorld?.negotiate)FGWorld.negotiate(id);else buyPlayer(id)}
function lineup(){let pitch=document.getElementById('pitch'),bench=document.getElementById('bench');if(!pitch||!bench)return;let f=document.getElementById('formation')?.value||'4-4-2',slots=FORM[f]||FORM['4-4-2'];if(!G.lineup||G.lineup.length!==11)G.lineup=G.roster.slice(0,11).map(x=>x[0]);let by=n=>G.roster.find(x=>x[0]===n);pitch.className='bfLineup';pitch.innerHTML=`<div class=bfTitle><b>ESCALAÇÃO ${f}</b><span>Escolhe um titular e depois um reserva</span></div>${slots.map((pos,i)=>{let p=by(G.lineup[i]);return `<button class="bfStarter ${selected===i?'sel':''}" onclick="FGManagerUI.select(${i})"><span>${pos}</span><b>${p?.[0]||'Vazio'}</b><strong>${p?.[2]||'-'}</strong></button>`}).join('')}`;let st=new Set(G.lineup);bench.innerHTML='<div class=bfTitle><b>RESERVAS</b><span>Posição • força</span></div>'+G.roster.filter(p=>!st.has(p[0])).map(p=>`<button class=bfReserve onclick="FGManagerUI.swap('${p[0].replace(/'/g,"\\'")}')"><b>${p[0]}</b><span>${p[1]}</span><strong>${p[2]}</strong></button>`).join('')}
function select(i){selected=i;lineup()}function swap(n){if(selected===null)return toast('Seleciona primeiro o titular.');G.lineup[selected]=n;selected=null;saveGame(false);lineup();toast('Substituição feita na escalação.')}
function calendar(){let host=document.getElementById('calendarList');if(!host)return;G.calendar=G.calendar||{monthIndex:0,viewMonth:0};let months=['Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],mi=G.calendar.viewMonth??G.calendar.monthIndex??0,games=[];(G.schedules?.[G.division]||[]).forEach(rd=>{let g=rd.find(x=>x.h===G.club||x.a===G.club);if(g)games.push(g)});host.innerHTML=`<div class=bfCal><button onclick="FGManagerUI.month(-1)">◀</button><b>${months[mi]} ${G.year}</b><button onclick="FGManagerUI.month(1)">▶</button></div>${games.slice(mi*4,mi*4+4).map((g,j)=>`<div class=bfGame><b>${String(mi*4+j+1).padStart(2,'0')}/${String(mi+3).padStart(2,'0')}</b><span>${g.h} x ${g.a}</span><strong>${g.played?`${g.hg} x ${g.ag}`:'A disputar'}</strong></div>`).join('')||'<div class=item>Sem partidas neste mês.</div>'}`}
function month(d){G.calendar=G.calendar||{monthIndex:0,viewMonth:0};G.calendar.viewMonth=Math.max(0,Math.min(9,(G.calendar.viewMonth??G.calendar.monthIndex??0)+d));calendar()}
function own(){window.renderMarket=market;window.renderLineup=lineup;window.renderCalendar=calendar;window.saveLineup=()=>{saveGame(false);toast('Escalação salva.')};sync();market();lineup();calendar()}
window.FGManagerUI={market,lineup,player,offer,select,swap,calendar,month,own,sync};let css=document.createElement('style');css.textContent=`.bfTitle{display:flex;justify-content:space-between;align-items:center;background:#171d18;border-bottom:2px solid #d8a52b;padding:10px}.bfMarket{display:grid;grid-template-columns:minmax(150px,1.5fr) 55px minmax(100px,1fr) 45px 105px 55px 80px;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #28332b}.bfLineup{display:block!important;min-height:0!important;width:100%!important;background:#0c120e!important;border:1px solid #354239!important;padding:0!important}.bfStarter,.bfReserve{width:100%;display:grid;grid-template-columns:55px 1fr 45px;gap:8px;align-items:center;border:0;border-bottom:1px solid #29342c;background:#111b15;color:white;padding:10px;text-align:left}.bfStarter span{font-weight:900;color:#d8a52b}.bfStarter.sel{background:#3b3215;outline:2px solid #d8a52b}.bfReserve{grid-template-columns:1fr 55px 45px}.bfCal{display:flex;justify-content:space-between;align-items:center;background:#171d18;padding:10px}.bfCal button{background:#d8a52b;border:0;padding:7px 14px;border-radius:6px}.bfGame{display:grid;grid-template-columns:65px 1fr 90px;padding:9px;border-bottom:1px solid #28332b}.bfGame strong{text-align:right}@media(max-width:720px){.bfMarket{grid-template-columns:1fr 50px 70px}.bfMarket span:nth-of-type(2),.bfMarket span:nth-of-type(3){display:none}}`;document.head.appendChild(css);setTimeout(own,2200);setInterval(()=>{if(window.G){window.renderMarket=market;window.renderLineup=lineup;window.renderCalendar=calendar}},1000)
})();