(()=>{
let halfOut=null;
function suspended(n){try{return (G.susp?.[pkey(n)]||0)>0}catch(e){return false}}
function ensureLineup(){try{ensureTactics?.()}catch(e){}G.lineup=Array.isArray(G.lineup)?G.lineup:[];G.lineup=G.lineup.filter(n=>G.roster.some(p=>p[0]===n)&&!suspended(n));while(G.lineup.length<11){let p=G.roster.find(x=>!G.lineup.includes(x[0])&&!suspended(x[0]));if(!p)break;G.lineup.push(p[0])}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function modal(comp,onGo){ensureLineup();if(window.FGLineupBrasfoot?.openPrematch)return FGLineupBrasfoot.openPrematch(comp,onGo);let old=document.getElementById('fgMatchModal');if(old)old.remove();let m=document.createElement('div');m.id='fgMatchModal';m.style='position:fixed;inset:0;background:#000d;z-index:99999;overflow:auto;padding:20px';m.innerHTML=`<div class="card" style="max-width:900px;margin:auto"><h2>⚽ ${comp} — PREPARAR PARTIDA</h2><p class=mut>Confirma os 11 antes de entrar em campo.</p><div class=row><button class="btn" onclick="go('lineup');document.getElementById('fgMatchModal').remove()">🧠 Abrir escalação</button><button class="btn green" id=fgConfirmMatch>▶ CONFIRMAR E JOGAR</button></div></div>`;document.body.appendChild(m);m.querySelector('#fgConfirmMatch').onclick=()=>{ensureLineup();if(G.lineup.length<11)return toast('Tu precisa escalar 11 jogadores disponíveis.');m.remove();onGo()}}
function halftime(){halfOut=null;renderHalf()}
function renderHalf(){let old=document.getElementById('fgHalf');if(old)old.remove();let outSet=new Set(G.matchSubbedOut||[]);let bench=(G.roster||[]).filter(p=>!G.lineup.includes(p[0])&&!suspended(p[0])&&!outSet.has(p[0])).slice(0,18);let starters=(G.lineup||[]).map(n=>(G.roster||[]).find(p=>p[0]===n)||[n,'?',0]);let m=document.createElement('div');m.id='fgHalf';m.style='position:fixed;inset:0;background:#000e;z-index:99999;overflow:auto;padding:16px';m.innerHTML=`<div class=card style="max-width:1050px;margin:auto"><h2 style="margin-bottom:4px">⏸️ INTERVALO / MEXER NO TIME</h2><p class=mut>Escolhe quem sai e depois quem entra. Jogador substituído não pode voltar nesta partida.</p><div class=row><select id=fgHalfFormation>${['4-4-2','4-3-3','4-2-3-1','3-5-2','4-1-4-1'].map(x=>`<option ${G.formation===x?'selected':''}>${x}</option>`).join('')}</select><select id=fgHalfMentality>${['Equilibrada','Ofensiva','Defensiva','Pressão alta','Contra-ataque'].map(x=>`<option ${G.mentality===x?'selected':''}>${x}</option>`).join('')}</select><span class=badge>Substituições: ${G.matchChanges||0}/5</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px"><div><h3>🟢 EM CAMPO</h3><div style="display:grid;gap:7px">${starters.map((p,i)=>`<button class="btn ${halfOut===p[0]?'green':''}" style="text-align:left;padding:12px" onclick="FGMatchday.pickOut('${String(p[0]).replaceAll("'","\\'")}')"><b>${i+1}. ${esc(p[0])}</b> <span class=mut>• ${esc(p[1])} • ${p[2]||0}</span>${halfOut===p[0]?'<br>⬅ VAI SAIR':''}</button>`).join('')}</div></div><div><h3>🪑 BANCO DISPONÍVEL</h3><div style="display:grid;gap:7px">${bench.map(p=>`<button class="btn" style="text-align:left;padding:12px" onclick="FGMatchday.pickIn('${String(p[0]).replaceAll("'","\\'")}')"><b>${esc(p[0])}</b> <span class=mut>• ${esc(p[1])} • ${p[2]||0}</span></button>`).join('')||'<div class=item>Sem jogadores disponíveis no banco.</div>'}</div>${outSet.size?`<h3>🚫 JÁ SAÍRAM</h3><div class=item>${[...outSet].map(esc).join(' • ')}</div>`:''}</div></div><h3>Vestiário</h3><div class=row><button class=btn onclick="FGMatchday.talk('elogio')">👏 Motivar</button><button class=btn onclick="FGMatchday.talk('cobrar')">🗣️ Cobrar</button><button class=btn onclick="FGMatchday.talk('xingar')">😡 Xingar</button></div><button class="btn green" style="margin-top:14px;width:100%" onclick="FGMatchday.resume()">▶ VOLTAR PARA O JOGO</button></div>`;document.body.appendChild(m)}
function pickOut(n){halfOut=halfOut===n?null:n;renderHalf()}
function pickIn(bench){if(!halfOut)return toast('Primeiro escolhe o jogador que vai sair.');if((G.matchChanges||0)>=5)return toast('Tu já usou as 5 substituições.');if((G.matchSubbedOut||[]).includes(bench))return toast('Esse jogador já saiu e não pode voltar nesta partida.');let idx=G.lineup.indexOf(halfOut);if(idx<0)return;let out=halfOut;G.lineup[idx]=bench;G.matchSubbedOut=Array.isArray(G.matchSubbedOut)?G.matchSubbedOut:[];if(!G.matchSubbedOut.includes(out))G.matchSubbedOut.push(out);G.matchChanges=(G.matchChanges||0)+1;halfOut=null;toast(`${out} saiu. ${bench} entrou.`);renderHalf()}
function talk(type){G.matchTalk=type;if(type==='elogio')toast('Tu motivou o grupo.');if(type==='cobrar')toast('Tu cobrou mais intensidade.');if(type==='xingar')toast('Tu deu uma baita bronca no vestiário.')}
function resume(){let f=document.getElementById('fgHalfFormation'),mt=document.getElementById('fgHalfMentality');if(f)G.formation=f.value;if(mt)G.mentality=mt.value;document.getElementById('fgHalf')?.remove();window.__fgResumeMatch?.()}
function compName(){return G.phase==='cup'?'Copinha Gaúcha':DIV[G.division]?.name||'Partida'}
function install(){if(!window.G)return;ensureLineup();window.FGLineupBrasfoot?.install?.();let btn=document.getElementById('playRound');if(btn){btn.dataset.fgMatchday='2';btn.onclick=()=>modal(compName(),()=>playRound(true))}let instant=document.getElementById('instantRound');if(instant){instant.dataset.fgMatchday='2';instant.onclick=()=>modal(compName(),()=>playRound(false))}}
window.FGMatchday={install,modal,halftime,pickOut,pickIn,talk,resume};setTimeout(install,2500);setInterval(install,1800)
})();