(()=>{
function suspended(n){try{return (G.susp?.[pkey(n)]||0)>0}catch(e){return false}}
function ensureLineup(){try{ensureTactics?.()}catch(e){}G.lineup=Array.isArray(G.lineup)?G.lineup:[];G.lineup=G.lineup.filter(n=>G.roster.some(p=>p[0]===n)&&!suspended(n));while(G.lineup.length<11){let p=G.roster.find(x=>!G.lineup.includes(x[0])&&!suspended(x[0]));if(!p)break;G.lineup.push(p[0])}}
function modal(comp,onGo){ensureLineup();if(window.FGLineupBrasfoot?.openPrematch)return FGLineupBrasfoot.openPrematch(comp,onGo);let old=document.getElementById('fgMatchModal');if(old)old.remove();let m=document.createElement('div');m.id='fgMatchModal';m.style='position:fixed;inset:0;background:#000d;z-index:99999;overflow:auto;padding:20px';m.innerHTML=`<div class="card" style="max-width:900px;margin:auto"><h2>⚽ ${comp} — PREPARAR PARTIDA</h2><p class=mut>Confirma os 11 antes de entrar em campo.</p><div class=row><button class="btn" onclick="go('lineup');document.getElementById('fgMatchModal').remove()">🧠 Abrir escalação</button><button class="btn green" id=fgConfirmMatch>▶ CONFIRMAR E JOGAR</button></div></div>`;document.body.appendChild(m);m.querySelector('#fgConfirmMatch').onclick=()=>{ensureLineup();if(G.lineup.length<11)return toast('Tu precisa escalar 11 jogadores disponíveis.');m.remove();onGo()}}
function halftime(){let old=document.getElementById('fgHalf');if(old)old.remove();let m=document.createElement('div');m.id='fgHalf';m.style='position:fixed;inset:0;background:#000d;z-index:99999;overflow:auto;padding:20px';m.innerHTML=`<div class=card style="max-width:850px;margin:auto"><h2>⏸️ INTERVALO</h2><p class=mut>Mexer agora pode mudar o jogo.</p><div class=row><select id=fgHalfFormation>${['4-4-2','4-3-3','4-2-3-1','3-5-2','4-1-4-1'].map(x=>`<option ${G.formation===x?'selected':''}>${x}</option>`).join('')}</select><select id=fgHalfMentality>${['Equilibrada','Ofensiva','Defensiva','Pressão alta','Contra-ataque'].map(x=>`<option ${G.mentality===x?'selected':''}>${x}</option>`).join('')}</select></div><h3>Banco / substituições</h3><div id=fgSubs>${G.roster.filter(p=>!G.lineup.includes(p[0])&&!suspended(p[0])).slice(0,16).map(p=>`<button class="btn" style="margin:3px" onclick="FGMatchday.sub('${String(p[0]).replaceAll("'","\\'")}')">${p[0]} • ${p[1]}</button>`).join('')}</div><h3>Vestiário</h3><div class=row><button class=btn onclick="FGMatchday.talk('elogio')">👏 Motivar</button><button class=btn onclick="FGMatchday.talk('cobrar')">🗣️ Cobrar</button><button class=btn onclick="FGMatchday.talk('xingar')">😡 Xingar</button></div><button class="btn green" style="margin-top:14px" onclick="FGMatchday.resume()">▶ VOLTAR PARA O 2º TEMPO</button></div>`;document.body.appendChild(m)}
function sub(bench){let out=prompt('Quem tu quer tirar?\n'+G.lineup.join('\n'));if(!out||!G.lineup.includes(out))return toast('Jogador não encontrado entre os titulares.');G.lineup[G.lineup.indexOf(out)]=bench;G.matchChanges=(G.matchChanges||0)+1;toast(`${out} saiu. ${bench} entrou.`);document.getElementById('fgHalf')?.remove();halftime()}
function talk(type){G.matchTalk=type;if(type==='elogio')toast('Tu motivou o grupo.');if(type==='cobrar')toast('Tu cobrou mais intensidade.');if(type==='xingar')toast('Tu deu uma baita bronca no vestiário.')}
function resume(){let f=document.getElementById('fgHalfFormation'),mt=document.getElementById('fgHalfMentality');if(f)G.formation=f.value;if(mt)G.mentality=mt.value;document.getElementById('fgHalf')?.remove();window.__fgResumeMatch?.()}
function compName(){return G.phase==='cup'?'Copinha Gaúcha':DIV[G.division]?.name||'Partida'}
function install(){if(!window.G)return;ensureLineup();window.FGLineupBrasfoot?.install?.();let btn=document.getElementById('playRound');if(btn){btn.dataset.fgMatchday='2';btn.onclick=()=>modal(compName(),()=>playRound(true))}let instant=document.getElementById('instantRound');if(instant){instant.dataset.fgMatchday='2';instant.onclick=()=>modal(compName(),()=>playRound(false))}}
window.FGMatchday={install,modal,halftime,sub,talk,resume};setTimeout(install,2500);setInterval(install,1800)
})();