(()=>{
function ensure(){return !!window.G}
function finalists(d){let po=G.playoffs?.[d];if(!po)return[];if(po.finalists?.length===2)return po.finalists;if(po.stage==='Final'&&po.games?.[0])return[po.games[0].h,po.games[0].a];return[]}
function capture(){if(!ensure()||!G.playoffs)return;G.seasonMovements=G.seasonMovements||{year:G.year};for(const d of ['A2','B']){let f=finalists(d);if(f.length===2)G.seasonMovements[d+'Finalists']=[...f]}if(G.tables?.A1)G.seasonMovements.A1Bottom=standing('A1').slice(-2).map(x=>x.t);if(G.tables?.A2)G.seasonMovements.A2Bottom=standing('A2').slice(-2).map(x=>x.t)}
function moveClubs(){capture();let m=G.seasonMovements||{},upB=m.BFinalists||[],upA2=m.A2Finalists||[],downA1=m.A1Bottom||[],downA2=m.A2Bottom||[];let A1=[...DIV.A1.clubs],A2=[...DIV.A2.clubs],B=[...DIV.B.clubs];A1=A1.filter(x=>!downA1.includes(x));A2=A2.filter(x=>!downA2.includes(x)&&!upA2.includes(x));B=B.filter(x=>!upB.includes(x));upA2.forEach(x=>{if(!A1.includes(x))A1.push(x)});downA1.forEach(x=>{if(!A2.includes(x))A2.push(x)});upB.forEach(x=>{if(!A2.includes(x))A2.push(x)});downA2.forEach(x=>{if(!B.includes(x))B.push(x)});DIV.A1.clubs=A1;DIV.A2.clubs=A2;DIV.B.clubs=B;if(A1.includes(G.club))G.division='A1';else if(A2.includes(G.club))G.division='A2';else G.division='B';G.db?.forEach(p=>{if(A1.includes(p.c))p.d='A1';else if(A2.includes(p.c))p.d='A2';else if(B.includes(p.c))p.d='B'});return{upB,upA2,downA1,downA2}}
function marketMovement(count=14){if(!G.db?.length)return[];let log=[];for(let k=0;k<count;k++){let candidates=G.db.filter(p=>p.c&&p.c!==G.club&&!p.real);if(!candidates.length)break;let p=candidates[Math.floor(Math.random()*candidates.length)],d=p.d||findDiv(p.c),clubs=(DIV[d]?.clubs||[]).filter(c=>c!==p.c&&c!==G.club);if(!clubs.length)continue;let dest=clubs[Math.floor(Math.random()*clubs.length)],old=p.c;p.c=dest;p.d=d;p.value=Math.max(p.value||0,Math.round((p.ov||40)*(p.ov||40)*(d==='A1'?900:d==='A2'?260:70)));log.push(`${p.n}: ${old} → ${dest}`)}if(window.FGWorld)try{FGWorld.generateYear(Number(G.year)+1)}catch(e){}G.offseasonMarket=log;log.slice(0,8).forEach(x=>addNews('Mercado de transferências',x));return log}
function startCupFixed(){if(!ensure())return;if(!G.cup){let champ=G.playoffs?.A1?.winner||standing('A1')[0]?.t,all=[...DIV.A1.clubs,...DIV.A2.clubs,...DIV.B.clubs];for(let i=all.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[all[i],all[j]]=[all[j],all[i]]}G.cup={gauchoChamp:champ,teams:all.slice(0,32),round:0,winner:null,log:[]}}G.phase='cup';G.seasonEnded=true;capture();saveGame(false);renderAll();go('cup')}
function addEndButton(){if(!ensure()||!G.seasonEnded||!G.cup?.winner)return;let hist=document.getElementById('historyList');if(!hist||document.getElementById('fgEndYear'))return;hist.insertAdjacentHTML('beforeend',`<div class="item" id="fgEndYear"><b>Temporada ${G.year} encerrada.</b><br><span class="mut">A Copinha terminou. Agora abre a janela de transferências, confirma acessos/rebaixamentos e inicia ${G.year+1}.</span><br><button class="btn green" style="margin-top:10px" onclick="FGSeasonFlow.endYear()">ENCERRAR ANO E IR PARA ${G.year+1}</button></div>`)}
function endYear(){if(!G.seasonEnded||!G.cup?.winner)return toast('Ainda existem competições para terminar.');if(!confirm(`Encerrar ${G.year}? O mercado vai se movimentar e a temporada ${G.year+1} será criada.`))return;let mv=moveClubs(),moves=marketMovement(16),old=G.year;G.year++;G.round=0;G.phase='league';G.playoffs=null;G.seasonEnded=false;G.cup=null;G.seasonMovements={year:G.year};G.sponsor=null;G.sponsorSeason={year:G.year,changes:0,locked:false,firstMatchPlayed:false};G.sponsorPayments={};G.calendar={monthIndex:0,roundInMonth:0,viewMonth:0};for(const d of ['A1','A2','B']){G.tables[d]={};DIV[d].clubs.forEach(c=>G.tables[d][c]={J:0,V:0,E:0,D:0,GP:0,GC:0,SG:0,P:0});G.schedules[d]=roundRobin(DIV[d].clubs)}money(-15000,'Custos de pré-temporada');addNews('Acessos e rebaixamentos',`Subiram da Série B: ${mv.upB.join(' e ')||'—'}. Subiram do Acesso: ${mv.upA2.join(' e ')||'—'}. Caíram do Gauchão: ${mv.downA1.join(' e ')||'—'}. Caíram do Acesso: ${mv.downA2.join(' e ')||'—'}.`);addNews('Janela de transferências',`${moves.length} movimentações aconteceram entre os clubes antes de ${G.year}.`);addNews('Nova temporada',`${G.year} começou. ${G.club} disputa ${DIV[G.division].name}.`);saveGame(false);renderAll();go('home')}
function repair(){if(!ensure())return;if(G.phase==='cup'||G.seasonEnded){if(!G.cup)startCupFixed();addEndButton();return}if(G.playoffs&&['A1','A2','B'].every(d=>G.playoffs[d]?.winner))startCupFixed()}
function install(){if(!ensure())return;let oldAdvance=window.advancePlayoffs;if(oldAdvance&&!window.__fgFlowAdvance){window.advancePlayoffs=function(){let r=oldAdvance.apply(this,arguments);capture();if(G.playoffs&&['A1','A2','B'].every(d=>G.playoffs[d]?.winner))startCupFixed();return r};window.__fgFlowAdvance=1}window.newSeason=endYear;repair()}
window.FGSeasonFlow={install,repair,capture,moveClubs,startCup:startCupFixed,endYear,marketMovement};setTimeout(install,1500);setInterval(repair,1000)
})();