(()=>{
function ensure(){return !!window.G}
function finalists(d){let po=G.playoffs?.[d];if(!po)return[];if(po.finalists?.length===2)return po.finalists;if(po.stage==='Final'&&po.games?.[0])return[po.games[0].h,po.games[0].a];return[]}
function capture(){if(!ensure()||!G.playoffs)return;G.seasonMovements=G.seasonMovements||{year:G.year};for(const d of ['A2','B']){let f=finalists(d);if(f.length===2)G.seasonMovements[d+'Finalists']=[...f]}if(G.tables?.A1)G.seasonMovements.A1Bottom=standing('A1').slice(-2).map(x=>x.t);if(G.tables?.A2)G.seasonMovements.A2Bottom=standing('A2').slice(-2).map(x=>x.t)}
function moveClubs(){capture();let m=G.seasonMovements||{},upB=m.BFinalists||[],upA2=m.A2Finalists||[],downA1=m.A1Bottom||[],downA2=m.A2Bottom||[];let A1=[...DIV.A1.clubs],A2=[...DIV.A2.clubs],B=[...DIV.B.clubs];A1=A1.filter(x=>!downA1.includes(x));A2=A2.filter(x=>!downA2.includes(x)&&!upA2.includes(x));B=B.filter(x=>!upB.includes(x));for(const x of upA2)if(!A1.includes(x))A1.push(x);for(const x of downA1)if(!A2.includes(x))A2.push(x);for(const x of upB)if(!A2.includes(x))A2.push(x);for(const x of downA2)if(!B.includes(x))B.push(x);DIV.A1.clubs=A1;DIV.A2.clubs=A2;DIV.B.clubs=B;if(A1.includes(G.club))G.division='A1';else if(A2.includes(G.club))G.division='A2';else G.division='B';G.db?.forEach(p=>{if(A1.includes(p.c))p.d='A1';else if(A2.includes(p.c))p.d='A2';else if(B.includes(p.c))p.d='B'});return{upB,upA2,downA1,downA2}}
function startCupFixed(){if(!ensure())return;if(!G.cup){let champ=G.playoffs?.A1?.winner||standing('A1')[0]?.t;let all=[...DIV.A1.clubs,...DIV.A2.clubs,...DIV.B.clubs];for(let i=all.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[all[i],all[j]]=[all[j],all[i]]}G.cup={gauchoChamp:champ,teams:all.slice(0,32),round:0,winner:null,log:[]}}G.phase='cup';G.seasonEnded=true;capture();saveGame(false);renderAll();go('cup')}
function repair(){if(!ensure())return;if(G.phase==='cup'||G.seasonEnded){if(!G.cup)startCupFixed();return}if(G.playoffs&&['A1','A2','B'].every(d=>G.playoffs[d]?.winner)){startCupFixed()}}
function install(){if(!ensure())return;let oldAdvance=window.advancePlayoffs;if(oldAdvance&&!window.__fgFlowAdvance){window.advancePlayoffs=function(){let r=oldAdvance.apply(this,arguments);capture();if(G.playoffs&&['A1','A2','B'].every(d=>G.playoffs[d]?.winner))startCupFixed();return r};window.__fgFlowAdvance=1}window.newSeason=function(){if(!G.seasonEnded||!G.cup?.winner)return toast('Termina a Copinha antes de encerrar o ano.');let mv=moveClubs();let oldYear=G.year;G.year++;G.round=0;G.phase='league';G.playoffs=null;G.seasonEnded=false;G.cup=null;G.seasonMovements={year:G.year};G.sponsor=null;G.sponsorSeason={year:G.year,changes:0,locked:false,firstMatchPlayed:false};G.sponsorPayments={};G.calendar={monthIndex:0,roundInMonth:0,viewMonth:0};for(const d of ['A1','A2','B']){G.tables[d]={};DIV[d].clubs.forEach(c=>G.tables[d][c]={J:0,V:0,E:0,D:0,GP:0,GC:0,SG:0,P:0});G.schedules[d]=roundRobin(DIV[d].clubs)}money(-15000,'Custos de pré-temporada');addNews('Acessos e rebaixamentos',`Subiram da Série B: ${mv.upB.join(' e ')||'—'}. Subiram do Acesso: ${mv.upA2.join(' e ')||'—'}. Caíram do Gauchão: ${mv.downA1.join(' e ')||'—'}. Caíram do Acesso: ${mv.downA2.join(' e ')||'—'}.`);addNews('Nova temporada',`${G.year} começou. ${G.club} disputa ${DIV[G.division].name}.`);saveGame(false);renderAll();go('home')};repair()}
window.FGSeasonFlow={install,repair,capture,moveClubs,startCup:startCupFixed};setTimeout(install,1800);setInterval(repair,1800)
})();